#!/bin/bash
set -ex

sudo snap install go --classic
sudo snap install terraform --classic
go install github.com/tebeka/go2xunit@v1.4.10

TF_JUJU_QA_CTRL="juju-maas-controller" TF_VAR_arch="amd64" TF_VAR_tags="juju,$1" go test -v -timeout=4h -run=TestQA_Minimal ./... |& tee test_results.raw

~/go/bin/go2xunit -input test_results.raw -output test_results.xml
