#!/bin/bash

sudo snap install go --classic

go install github.com/tebeka/go2xunit@v1.4.10

go test -v -timeout=60m ./... |& tee test_results.raw

~/go/bin/go2xunit -input test_results.raw -output test_results.xml
